### ISSUE TITLE
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

### ISSUE THREAD

**Issue by mluerig** [biomedisa/biomedisa#1]
tried to run the DL examples (Windows 10 / 2x RTX2080Ti /64GB RAM / Python 3.7 env), but when running `python biomedisa_deeplearning.py heart label -train -epochs 200 -bs 24` I get following error:

```
Microsoft Windows [Version 10.0.19042.985]
(c) Microsoft Corporation. All rights reserved.

D:\workspace\git-repos\biomedisa\demo>conda activate biomedisa

(biomedisa) D:\workspace\git-repos\biomedisa\demo>python biomedisa_deeplearning.py heart label -train -epochs 200 -bs 24
2021-05-26 19:24:47.891516: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "biomedisa_deeplearning.py", line 30, in <module>
    from keras_helper import *
  File "D:\workspace\git-repos\biomedisa\demo\keras_helper.py", line 30, in <module>
    from keras.optimizers import SGD
  File "C:\Anaconda3\envs\biomedisa\lib\site-packages\keras\__init__.py", line 20, in <module>
    from . import initializers
  File "C:\Anaconda3\envs\biomedisa\lib\site-packages\keras\initializers\__init__.py", line 124, in <module>
    populate_deserializable_objects()
  File "C:\Anaconda3\envs\biomedisa\lib\site-packages\keras\initializers\__init__.py", line 82, in populate_deserializable_objects
    generic_utils.populate_dict_with_module_objects(
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
```

I'll give linux a try once I have the time.

**Comment by biomedisa** [comment]
Which Tensorflow version and which Keras version are you using?

**Comment by mluerig** [comment]
Keras==2.4.3 
tensorflow==2.5.0 (I also tried 2.2.2 as per this [SO post](https://stackoverflow.com/questions/61137954/attributeerror-module-tensorflow-python-keras-utils-generic-utils-has-no-attr)

**Comment by biomedisa** [comment]
Biomedisa is currently running with TensorFlow 2.4.1 and Keras 2.4.3. Please try to downgrade to this TensorFlow version
`pip3 install tensorflow-gpu==2.4.3`

**Comment by mluerig** [comment]
after downgrading to `2.4.1` I got this error:

      Attempting uninstall: tensorflow-gpu
        Found existing installation: tensorflow-gpu 2.5.0
        Uninstalling tensorflow-gpu-2.5.0:
          Successfully uninstalled tensorflow-gpu-2.5.0
    ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
    tensorflow 2.5.0 requires gast==0.4.0, but you have gast 0.3.3 which is incompatible.
    tensorflow 2.5.0 requires grpcio~=1.34.0, but you have grpcio 1.32.0 which is incompatible.
    tensorflow 2.5.0 requires h5py~=3.1.0, but you have h5py 2.10.0 which is incompatible.
    tensorflow 2.5.0 requires tensorflow-estimator<2.6.0,>=2.5.0rc0, but you have tensorflow-estimator 2.4.0 which is incompatible.
    Successfully installed gast-0.3.3 grpcio-1.32.0 h5py-2.10.0 tensorflow-estimator-2.4.0 tensorflow-gpu-2.4.1

still, it looks like the downgrade worked - but then I got this error

    (biomedisa) D:\workspace\git-repos\biomedisa\demo>python biomedisa_deeplearning.py heart label -train -epochs 200 -bs 24
    2021-05-28 17:33:36.773808: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
    Traceback (most recent call last):
      File "biomedisa_deeplearning.py", line 30, in <module>
        from keras_helper import *
      File "D:\workspace\git-repos\biomedisa\demo\keras_helper.py", line 30, in <module>
        from keras.optimizers import SGD
      File "C:\Anaconda3\envs\biomedisa\lib\site-packages\keras\__init__.py", line 20, in <module>
        from . import initializers
      File "C:\Anaconda3\envs\biomedisa\lib\site-packages\keras\initializers\__init__.py", line 124, in <module>
        populate_deserializable_objects()
      File "C:\Anaconda3\envs\biomedisa\lib\site-packages\keras\initializers\__init__.py", line 49, in populate_deserializable_objects
        LOCAL.GENERATED_WITH_V2 = tf.__internal__.tf2.enabled()
    AttributeError: module 'tensorflow.compat.v2.__internal__' has no attribute 'tf2'

**Comment by biomedisa** [comment]
Could you try to remove `tensorflow` and  `tensorflow-gpu` first, and then reinstall only `tensorflow-gpu`. 
```
pip3 uninstall tensorflow
pip3 uninstall tensorflow-gpu
pip3 install tensorflow-gpu==2.4.1
```
There could be a version conflict here.

**Comment by mluerig** [comment]
I don't have access to the machine now, but I'll try next week

**Comment by mluerig** [comment]
now I get this:

    (biomedisa) D:\workspace\git-repos\biomedisa\demo>python biomedisa_deeplearning.py heart label -train -epochs 200 -bs 24
    2021-06-15 07:40:22.679813: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
    Traceback (most recent call last):
      File "biomedisa_deeplearning.py", line 30, in <module>
        from keras_helper import *
      File "D:\workspace\git-repos\biomedisa\demo\keras_helper.py", line 30, in <module>
        from keras.optimizers import SGD
      File "C:\Anaconda3\envs\biomedisa\lib\site-packages\keras\__init__.py", line 20, in <module>
        from . import initializers
      File "C:\Anaconda3\envs\biomedisa\lib\site-packages\keras\initializers\__init__.py", line 124, in <module>
        populate_deserializable_objects()
      File "C:\Anaconda3\envs\biomedisa\lib\site-packages\keras\initializers\__init__.py", line 49, in populate_deserializable_objects
        LOCAL.GENERATED_WITH_V2 = tf.__internal__.tf2.enabled()
    AttributeError: module 'tensorflow.compat.v2.__internal__' has no attribute 'tf2'

**Comment by biomedisa** [comment]
1. Before proceeding, please check if an update of your Biomedisa Git repository helps (since I removed Keras which is now built into TensorFlow).
```
cd git/biomedisa
git pull
```
2. Even though you are using Anaconda, I am assuming that you have CUDA 11.0 installed as in the Biomedisa documentation. Please make sure that you have installed the correct cuDNN 8.x.x version (https://developer.nvidia.com/rdp/cudnn-archive) for CUDA 11.0 (+ tensorflow-gpu == 2.4.1).
3. Alternatively, you can try installing CUDA & cuDNN with Anaconda (this only supports CUDA 10.1).
```
conda install -c anaconda cudatoolkit=10.1
conda install -c anaconda cudnn=7.6
pip install tensorflow-gpu==2.3.0
```
4. Also, make sure that h5py is no higher than 2.10 in either case
`pip install h5py==2.10.0`

**Comment by mluerig** [comment]
ok, there is progress. the training is started, but it ends after the first epoch with this error:

    (biomedisa) D:\workspace\git-repos\biomedisa>git pull
    remote: Enumerating objects: 34, done.
    remote: Counting objects: 100% (34/34), done.
    remote: Compressing objects: 100% (2/2), done.
    remote: Total 21 (delta 19), reused 21 (delta 19), pack-reused 0
    Unpacking objects: 100% (21/21), 3.42 KiB | 3.00 KiB/s, done.
    From https://github.com/biomedisa/biomedisa
       a0172d7..6d2d9c2  master     -> origin/master
    Updating a0172d7..6d2d9c2
    Fast-forward
     README.md                                  |  55 +++++---
     README/INSTALL_CLUSTER.txt                 |   8 +-
     README/INSTALL_UBUNTU_18.04.5.md           |  12 +-
     README/INSTALL_WINDOWS_10.md               |   8 +-
     biomedisa_app/templates/publications.html  | 195 +++++++++++++++--------------
     biomedisa_features/DataGenerator.py        |   6 +-
     biomedisa_features/PredictDataGenerator.py |   4 +-
     biomedisa_features/keras_helper.py         |  20 +--
     demo/DataGenerator.py                      |   6 +-
     demo/PredictDataGenerator.py               |   4 +-
     demo/keras_helper.py                       |  10 +-
     11 files changed, 183 insertions(+), 145 deletions(-)
    
    (biomedisa) D:\workspace\git-repos\biomedisa>cd demo
    
    (biomedisa) D:\workspace\git-repos\biomedisa\demo>python biomedisa_deeplearning.py heart label -train -epochs 200 -bs 24
    2021-06-21 16:54:45.512033: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
    2021-06-21 16:54:48.738095: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
    2021-06-21 16:54:48.739843: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
    2021-06-21 16:54:48.796622: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
    pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
    coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 11,00GiB deviceMemoryBandwidth: 573,69GiB/s
    2021-06-21 16:54:48.796981: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 1 with properties:
    pciBusID: 0000:02:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
    coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 11,00GiB deviceMemoryBandwidth: 573,69GiB/s
    2021-06-21 16:54:48.797977: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
    2021-06-21 16:54:49.217939: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
    2021-06-21 16:54:49.218097: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
    2021-06-21 16:54:49.502279: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
    2021-06-21 16:54:49.533010: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
    2021-06-21 16:54:49.740812: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
    2021-06-21 16:54:49.939470: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
    2021-06-21 16:54:49.957391: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
    2021-06-21 16:54:49.957871: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0, 1
    2021-06-21 16:54:49.961248: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
    To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
    2021-06-21 16:54:50.208531: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
    pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
    coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 11,00GiB deviceMemoryBandwidth: 573,69GiB/s
    2021-06-21 16:54:50.208652: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 1 with properties:
    pciBusID: 0000:02:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
    coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 11,00GiB deviceMemoryBandwidth: 573,69GiB/s
    2021-06-21 16:54:50.209047: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
    2021-06-21 16:54:50.209112: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
    2021-06-21 16:54:50.209173: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
    2021-06-21 16:54:50.209241: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
    2021-06-21 16:54:50.209572: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
    2021-06-21 16:54:50.209953: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
    2021-06-21 16:54:50.210254: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
    2021-06-21 16:54:50.210315: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
    2021-06-21 16:54:50.210600: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0, 1
    2021-06-21 16:54:51.350112: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
    2021-06-21 16:54:51.350235: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 1
    2021-06-21 16:54:51.350547: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N N
    2021-06-21 16:54:51.350633: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 1:   N N
    2021-06-21 16:54:51.351449: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9416 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
    2021-06-21 16:54:51.353291: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 9417 MB memory) -> physical GPU (device: 1, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:02:00.0, compute capability: 7.5)
    2021-06-21 16:54:51.354409: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
    Number of devices: 2
    2021-06-21 16:55:02.369732: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:656] In AUTO-mode, and switching to DATA-based sharding, instead of FILE-based sharding as we cannot find appropriate reader dataset op(s) to shard. Error: Did not find a shardable source, walked to a node which is not a dataset: name: "FlatMapDataset/_2"
    op: "FlatMapDataset"
    input: "TensorDataset/_1"
    attr {
      key: "Targuments"
      value {
        list {
        }
      }
    }
    attr {
      key: "f"
      value {
        func {
          name: "__inference_Dataset_flat_map_flat_map_fn_3629"
        }
      }
    }
    attr {
      key: "output_shapes"
      value {
        list {
          shape {
            dim {
              size: -1
            }
            dim {
              size: -1
            }
            dim {
              size: -1
            }
            dim {
              size: -1
            }
            dim {
              size: -1
            }
          }
          shape {
            dim {
              size: -1
            }
            dim {
              size: -1
            }
            dim {
              size: -1
            }
            dim {
              size: -1
            }
            dim {
              size: -1
            }
          }
        }
      }
    }
    attr {
      key: "output_types"
      value {
        list {
          type: DT_FLOAT
          type: DT_FLOAT
        }
      }
    }
    . Consider either turning off auto-sharding or switching the auto_shard_policy to DATA to shard this dataset. You can do this by creating a new `tf.data.Options()` object then setting `options.experimental_distribute.auto_shard_policy = AutoShardPolicy.DATA` before applying the options object to the dataset via `dataset.with_options(options)`.
    2021-06-21 16:55:02.386501: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
    Epoch 1/200
    Error: No OpKernel was registered to support Op 'NcclAllReduce' used by {{node SGD/NcclAllReduce}} with these attrs: [reduction="sum", shared_name="c1", T=DT_FLOAT, num_devices=2]
    Registered devices: [CPU, GPU]
    Registered kernels:
      <no registered kernels>
    
             [[SGD/NcclAllReduce]] [Op:__inference_train_function_27300]
    Total calculation time: 22 sec
    
    (biomedisa) D:\workspace\git-repos\biomedisa\demo>

**Comment by biomedisa** [comment]
For people passing by: The problem was due to using multi-GPU on Windows which does not support NCCL. The solution was to replace
```
strategy = tf.distribute.MirroredStrategy()
```
by
```
strategy = tf.distribute.MirroredStrategy(tf.distribute.HierarchicalCopyAllReduce())
```
as discussed here https://github.com/tensorflow/tensorflow/issues/33656.
If you are using Biomedisa, all you need to do is update your repository
```
cd git/biomedisa
git pull
```
